{% set version = "0.7-4" %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-tm
  version: {{ version|replace("-", "_") }}

source:
  fn: tm_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/tm_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/tm/tm_{{ version }}.tar.gz
  sha256: ca2783b5d481e28e05b6856b38b7f3169e960e2f8997bb5046aff040b3026cef

build:
  merge_build_host: True  # [win]
  number: 1
  skip: true  # [win32]

  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - posix                # [win]
    - {{ compiler('c') }}        # [unix]
    - {{ compiler('m2w64_c') }}  # [win]
    - {{ compiler('cxx') }}        # [unix]
    - {{ compiler('m2w64_cxx') }}  # [win]
  host:
    - r-base
    - r-bh
    - r-nlp >=0.1_6.2
    - r-rcpp
    - r-slam >=0.1_37
    - r-xml2

  run:
    - r-base
    - r-xml2
    - r-bh
    - r-nlp >=0.1_6.2
    - r-rcpp
    - r-slam >=0.1_37

test:
  commands:
    - $R -e "library('tm')"  # [not win]
    - "\"%R%\" -e \"library('tm')\""  # [win]

about:
  home: http://tm.r-forge.r-project.org/
  license: GPL-3
  summary: A framework for text mining applications within R.
  license_family: GPL3

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
