{% set version = "0.7-8" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-tm
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/tm_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/tm/tm_{{ version }}.tar.gz
  sha256: b1eb1683d956db1a207b61cc086ae08b3ca7f46b6b8bc46d09ba5a4fafa66256

build:
  merge_build_host: true  # [win]
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-bh
    - r-nlp >=0.2_0
    - r-rcpp
    - r-slam >=0.1_37
    - r-xml2
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-bh
    - r-nlp >=0.2_0
    - r-rcpp
    - r-slam >=0.1_37
    - r-xml2

test:
  commands:
    - $R -e "library('tm')"           # [not win]
    - "\"%R%\" -e \"library('tm')\""  # [win]

about:
  home: http://tm.r-forge.r-project.org/
  license: GPL-3.0-only
  summary: A framework for text mining applications within R.
  license_family: GPL3
  license_file: {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: tm
# Title: Text Mining Package
# Version: 0.7-6
# Date: 2018-12-21
# Authors@R: c(person("Ingo", "Feinerer", role = c("aut", "cre"), email = "feinerer@logic.at", comment = c(ORCID = "0000-0001-7656-8338")), person("Kurt", "Hornik", role = "aut", comment = c(ORCID = "0000-0003-4198-9911")), person("Artifex Software, Inc.", role = c("ctb", "cph"), comment = "pdf_info.ps taken from GPL Ghostscript"))
# Depends: R (>= 3.2.0), NLP (>= 0.2-0)
# Imports: Rcpp, parallel, slam (>= 0.1-37), stats, tools, utils, graphics, xml2
# LinkingTo: BH, Rcpp
# Suggests: antiword, filehash, methods, pdftools, Rcampdf, Rgraphviz, Rpoppler, SnowballC, testthat, tm.lexicon.GeneralInquirer
# SystemRequirements: C++11
# Description: A framework for text mining applications within R.
# License: GPL-3
# URL: http://tm.r-forge.r-project.org/
# Additional_repositories: https://datacube.wu.ac.at
# NeedsCompilation: yes
# Packaged: 2018-12-21 13:10:14 UTC; hornik
# Author: Ingo Feinerer [aut, cre] (<https://orcid.org/0000-0001-7656-8338>), Kurt Hornik [aut] (<https://orcid.org/0000-0003-4198-9911>), Artifex Software, Inc. [ctb, cph] (pdf_info.ps taken from GPL Ghostscript)
# Maintainer: Ingo Feinerer <feinerer@logic.at>
# Repository: CRAN
# Date/Publication: 2018-12-21 13:55:26 UTC
