{% set version = '0.7-5' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-tm
  version: {{ version|replace("-", "_") }}

source:
  fn: tm_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/tm_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/tm/tm_{{ version }}.tar.gz
  sha256: 5d3150d2bf0964405be07c30aa6be3c415bf56e24e6041ac77ccb9de8c9ca317

build:
  merge_build_host: True  # [win]
  number: 0
  skip: true  # [win32]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('cxx') }}      # [not win]
    - {{native}}toolchain        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make
    - {{posix}}sed               # [win]
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-bh
    - r-nlp >=0.1_6.2
    - r-rcpp
    - r-slam >=0.1_37
    - r-xml2
  run:
    - r-base
    - {{native}}gcc-libs         # [win]
    - r-bh
    - r-nlp >=0.1_6.2
    - r-rcpp
    - r-slam >=0.1_37
    - r-xml2

test:
  commands:
    - $R -e "library('tm')"           # [not win]
    - "\"%R%\" -e \"library('tm')\""  # [win]

about:
  home: http://tm.r-forge.r-project.org/
  license: GPL-3
  summary: A framework for text mining applications within R.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'  # [unix]
  license_file: '{{ environ["PREFIX"] }}\R\share\licenses\GPL-3'  # [win]

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - dbast
