# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_r_base3.4.1target_platformosx-64
    - CONFIG=osx_r_base3.5.1target_platformosx-64

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "DbjfSj1vnt+xc69KxGrHINihEAxrJlYMrJe3RBYbu5Zw3IyFxfxPpGi+hgx9Tlp1uIjNOYqQJtg2OQQ0mwE7ewTz9D9vfwCI9IG07ha0pHcyer3u7QT6Z6AvcLAR44RdWLnqsva9veUu7ShomKSoR00Eg5Rd1RlYb6UUT/e21WrOckpW6LAKvgUYgkPP5nxTrvulu3C9QR49+c/PL86JpybUcAtTAIxIuO8kMSTIJ3WtAwfhg5/xhasz1iox+l9WMsPoBmqSWaIyl2Ht7lKH61cF1l+7dt0kTnoa4/eYUklfAiQsFqYNmzo1MlEvGuIKwyWcd+ykxPK7HL1ZhajNFm25eonBuoXKu26HRZHMID07QFVW7VUNmhQrUYw7G2B6EkFABwBOtmCax6uEJKGt+SptDdMkQjuhZRAjpmfnfFtsywdqztxA/3X4Z7CDrdPlzQcBLDu+MYXoerh8vgJ40akQC/CYlkt+FfKeK2TS0xBXDbKia+YcHEJ9s6qHI7Kr8BMbydIs929o0Ni04tXYI41epMXOcmMpwdDsivWcbe3fFdrLaU3T/UN+wUt74H/OQhhJjvX9p8q1+uUndqx5pARHf/YuNh+7Gi3oAyhezp4Nu7sp1sH3RWxHp8TH3/W82jRTf8T0LSk7MpruhVxK3UUf5vHGsIMD2C/ugblINb4="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
