appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: DbjfSj1vnt+xc69KxGrHINihEAxrJlYMrJe3RBYbu5Zw3IyFxfxPpGi+hgx9Tlp1uIjNOYqQJtg2OQQ0mwE7ewTz9D9vfwCI9IG07ha0pHcyer3u7QT6Z6AvcLAR44RdWLnqsva9veUu7ShomKSoR00Eg5Rd1RlYb6UUT/e21WrOckpW6LAKvgUYgkPP5nxTrvulu3C9QR49+c/PL86JpybUcAtTAIxIuO8kMSTIJ3WtAwfhg5/xhasz1iox+l9WMsPoBmqSWaIyl2Ht7lKH61cF1l+7dt0kTnoa4/eYUklfAiQsFqYNmzo1MlEvGuIKwyWcd+ykxPK7HL1ZhajNFm25eonBuoXKu26HRZHMID07QFVW7VUNmhQrUYw7G2B6EkFABwBOtmCax6uEJKGt+SptDdMkQjuhZRAjpmfnfFtsywdqztxA/3X4Z7CDrdPlzQcBLDu+MYXoerh8vgJ40akQC/CYlkt+FfKeK2TS0xBXDbKia+YcHEJ9s6qHI7Kr8BMbydIs929o0Ni04tXYI41epMXOcmMpwdDsivWcbe3fFdrLaU3T/UN+wUt74H/OQhhJjvX9p8q1+uUndqx5pARHf/YuNh+7Gi3oAyhezp4Nu7sp1sH3RWxHp8TH3/W82jRTf8T0LSk7MpruhVxK3UUf5vHGsIMD2C/ugblINb4=}
